version: '3.8'

services:
  postgres_test_db:
    image: postgres:latest
    container_name: postgres_test_db
    environment:
      POSTGRES_DB: db_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    depends_on:
      - fastapi_test_app
    expose:
      - "5432"
    networks:
      - backend

  fastapi_test_app:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    container_name: fastapi_test_app
    ports:
      - "8001:8001"
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: react_app
    ports:
      - "3001:3000"
    networks:
      - backend

networks:
  backend:
